development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  user: root
  database: review_me_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: review_me_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: review_me_production
  pool: 25

